import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/components/ReduxProvider";
import AppNavbar from "@/components/NavbarWrap";




export const metadata: Metadata = {
  title: "Job-portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  
 return (
    <html lang="en">
      <body>
        
        <ReduxProvider>
          <AppNavbar> 
          {children}
          </AppNavbar> 
        </ReduxProvider>
      </body>
    </html>
  );
}
