import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/components/ReduxProvider";
import AppNavbar from "@/components/NavbarWrap";
import { AuthProvider } from "@/Context/AuthContext";
import AuthBootstrapper from "@/components/common/authboothstaper";




export const metadata: Metadata = {
  title: "Job-portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  
 return (
    <html lang="en">
      <body>
        
        <ReduxProvider>
          <AuthBootstrapper />
           <AuthProvider> 
             <AppNavbar> 
              {children}
             </AppNavbar> 
           </AuthProvider> 
        </ReduxProvider>
      </body>
    </html>
  );
}
