import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/ReduxProvider";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Job-portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
    <html lang="en">
      <body>
        <Navbar/> 
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
